"""Feedback derivation: compare realize output against feedforward plan.

Called from the realize pipeline after post-reflect completes.  Emits
FEEDBACK_RECONCILE proposals when code generated by Claude diverges from the
plan captured in the accepted FEEDFORWARD_FILL transaction.

Divergences detected:
  - plan files not modified: the plan named a file but Claude didn't touch it
  - unexpected files modified: Claude touched a file not in the plan
"""
from __future__ import annotations

from pathlib import Path


_CODE_EXTENSIONS = frozenset({
    ".py", ".ts", ".tsx", ".js", ".jsx", ".go", ".rs", ".java", ".rb", ".c", ".cpp", ".h",
})


def _find_feedforward_tx(feature_uuid: str, store):
    """Return the most recent FEEDFORWARD_FILL tx for feature_uuid, or None."""
    from codoc.model.transaction import TransactionKind

    txs = store.list_transactions(proposal=None, feature_uuid=feature_uuid, limit=0)
    matching = [
        tx for tx in txs
        if tx.kind == TransactionKind.FEEDFORWARD_FILL
    ]
    if not matching:
        return None
    return max(matching, key=lambda tx: tx.hlc.to_str())


def derive_feedback_proposals(
    feature_uuids: list[str],
    modified_files: list[str],
    codoc_dir: str,
) -> int:
    """Compare what Claude actually modified against each feature's feedforward plan.

    Opens its own stores, writes FEEDBACK_RECONCILE proposals, re-renders the
    tree, and returns the number of proposals emitted.

    Parameters
    ----------
    feature_uuids:
        UUIDs of the features that were in the realize run.
    modified_files:
        Repo-relative paths of files Claude modified.
    codoc_dir:
        Path to the ``.codoc/`` directory.
    """
    from codoc.pipelines.intentional.runner import open_stores
    from codoc.model.transaction import Transaction, TransactionKind
    from codoc.projection.tree_codoc import write_tree

    store, tx_log, jsonl_log = open_stores(codoc_dir)
    proposals_emitted = 0

    modified_code = {
        f for f in modified_files
        if Path(f).suffix in _CODE_EXTENSIONS
    }

    try:
        for feature_uuid in feature_uuids:
            feature = store.get_feature(feature_uuid)
            if feature is None or feature.retired:
                continue

            ff_tx = _find_feedforward_tx(feature_uuid, store)
            if ff_tx is None:
                continue

            plan_target_files: list[str] = ff_tx.payload.get("target_files", [])
            if not plan_target_files:
                continue

            plan_set = set(plan_target_files)
            missing = sorted(plan_set - modified_code)
            unexpected = sorted(modified_code - plan_set)

            if not missing and not unexpected:
                continue

            divergences: list[str] = []
            if missing:
                divergences.append(f"plan files not modified: {', '.join(missing[:5])}")
            if unexpected:
                divergences.append(f"unexpected files modified: {', '.join(unexpected[:5])}")

            note = "; ".join(divergences)
            old_rationale = feature.rationale or ""
            new_rationale = f"{old_rationale} [generated: {note}]".strip()

            hlc = tx_log._tick()
            tx = Transaction(
                hlc=hlc,
                parent_hlcs=[ff_tx.hlc],
                kind=TransactionKind.FEEDBACK_RECONCILE,
                payload={
                    "feature_uuid": feature_uuid,
                    "slug": feature.slug,
                    "divergence_note": note,
                    "old_rationale": old_rationale,
                    "new_rationale": new_rationale,
                    "missing_files": missing,
                    "unexpected_files": unexpected,
                },
                author="feedback",
                proposal=True,
            )
            stamped = tx_log.append_proposal(tx)
            jsonl_log.append(stamped)
            proposals_emitted += 1

        if proposals_emitted > 0:
            write_tree(codoc_dir, store, tx_log)

    finally:
        store.close()

    return proposals_emitted
